parent: !include default.yaml
collision_avoidance:
  external_collision_avoidance:
    override:
      odom_z_joint: # this affects all links between this and the next controlled joint
        hard_threshold: 0.02 # at this distance in [cm] that can not be surpassed
        soft_threshold: 0.7 # robot links are pushed to that distance, but it can be overpowered with high weight constraints
action_server:
  base:
    plugin: SendFollowJointTrajectoryDiffDrive
    namespace: /base_controller/follow_joint_trajectory
    state_topic: /base_controller/state
  torso:
    plugin: SendFollowJointTrajectory
    namespace: /torso_controller/follow_joint_trajectory
    state_topic: /torso_controller/state
  neck:
    plugin: SendFollowJointTrajectory
    namespace: /head_controller/follow_joint_trajectory
    state_topic: /head_controller/state
  left_arm:
    plugin: SendFollowJointTrajectory
    namespace: /arm_left_controller/follow_joint_trajectory
    state_topic: /arm_left_controller/state
  right_arm:
    plugin: SendFollowJointTrajectory
    namespace: /arm_right_controller/follow_joint_trajectory
    state_topic: /arm_right_controller/state
